version: '3.7'
services:
  mongodb:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 3165TNHNAA97F9uZfzsT
      MONGO_INITDB_ROOT_PASSWORD: 3169TGd1Uu2QWtFlVkGJ
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
    networks:
      - ac_default
networks:
  ac_default:
    driver: bridge

